#  Dockerfile Development for Node Express Backend

FROM node:12.18.2-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --silent

COPY . .

EXPOSE 4949

CMD ["npm", "run", "server"]